# Generated by Django 3.0.2 on 2023-05-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCost',
        ),
    ]
