# Generated by Django 3.0.2 on 2023-05-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_delete_servicecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид доходов',
                'verbose_name_plural': 'Виды доходов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expensesplan',
            options={'ordering': ['purchase_date', 'expense'], 'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы планируемые'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='IncomePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True, verbose_name='Величина доходов')),
                ('income_date', models.DateField(verbose_name='Дата доходов')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Incomes', verbose_name='Вид доходов')),
            ],
            options={
                'verbose_name': 'Доходы',
                'verbose_name_plural': 'Доходы планируемые',
                'ordering': ['name'],
            },
        ),
    ]
