# Generated by Django 3.0.2 on 2023-05-30 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20230530_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeFactoryBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_start', models.TimeField(verbose_name='Начало урока')),
                ('lesson_date', models.DateField(verbose_name='Дата урока')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('lesson_price', models.FloatField(verbose_name='Цена урока')),
                ('filling', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность занятия')),
                ('amount', models.FloatField(verbose_name='Стоимость')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Incomes', verbose_name='Вид доходов')),
            ],
            options={
                'verbose_name': 'Доходы',
                'verbose_name_plural': 'Доходы от бордов',
                'ordering': ['name'],
            },
        ),
    ]
