# Generated by Django 3.0.2 on 2023-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20230528_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecost',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата расхода'),
        ),
    ]
