# Generated by Django 3.0.2 on 2023-05-30 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_incomefactoryboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomeplan',
            options={'ordering': ['income_date', 'name'], 'verbose_name': 'Доходы', 'verbose_name_plural': 'Доходы планируемые'},
        ),
        migrations.AlterField(
            model_name='incomefactoryboard',
            name='filling',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Наполненность занятия'),
        ),
    ]
