# Generated by Django 3.0.2 on 2023-05-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20230529_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceGroup',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
